### ISSUE TITLE
how to include in gradle?

### ISSUE THREAD

**Issue by sijangurung** [Yalantis/Taurus#4]
I am trying to implement . 
- I tried by including pulltorefresh library in gradle..but it is not maintained til date.
- also i tried by downloading the whole library and including it as module in my project, but it seems to have problems with that too.
  Can you please explain process to use this awesome library in my project ( PS: I am using android studio with gradle support)
- Thanks

**Comment by TeeRawk** [comment]
Hello @sijangurung , try this 
    compile 'com.yalantis:pulltorefresh:1.0.0'
